version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.11
    working_directory: ~/board

    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ .Branch }}-{{ checksum "package.json" }}
            - dependency-cache-{{ .Branch }}
            - dependency-cache
      - run:
          command: sudo apt-get install libXcomposite
      - run:
          name: "Install Dependencies"
          command: |
            npm ci
      - save_cache:
          key: dependency-cache-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      - run:
          name: "Run Checks"
          command: npm run lint
      - run:
          name: "Vulnerability Checks"
          command: npm audit
      - run:
          name: "Run Unit Tests"
          command: npm run test
      - run:
          name: "Run Journey Tests"
          command: npm run test:cypress
