version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.11
    working_directory: ~/board

    steps:
      - checkout
      # - restore_cache:
      #     key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: "Install Dependencies"
          command: |
            npm install
      # - save_cache:
      #     key: dependency-cache-{{ checksum "package.json" }}
      #     paths:
      #       - node_modules
      - run:
          name: "Run Checks"
          command: npm run lint
      - run:
          name: "Vulnerability Checks"
          command: npm audit
      - run:
          name: "Run Unit Tests"
          command: npm run test
      - run:
          name: "Run Journey Tests"
          command: npm run test:cypress
